modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPLV3.0"
[[mods]]
modId="traversable_leaves"
version="${file.jarVersion}"
displayName="Traversable Leaves"
logoFile="traversable.png"
credits=""
authors="Dreu and FleeceComrade"
description='''
Makes leaves traversable! You can move through them slowly, even up and down!
Config Options:
- Which leaves you want to be traversable, even modded leaves.
- Which entities you want to allow to traverse leaves.
'''
[[dependencies.traversable_leaves]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.traversable_leaves]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
